# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ireton/ComputerGraphics/OpenGL/ShaderPrograms/water

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ireton/ComputerGraphics/OpenGL/ShaderPrograms/water

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ireton/ComputerGraphics/OpenGL/ShaderPrograms/water/CMakeFiles /home/ireton/ComputerGraphics/OpenGL/ShaderPrograms/water//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ireton/ComputerGraphics/OpenGL/ShaderPrograms/water/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WaterShader

# Build rule for target.
WaterShader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WaterShader
.PHONY : WaterShader

# fast build rule for target.
WaterShader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/build
.PHONY : WaterShader/fast

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/camera.cpp.s
.PHONY : camera.cpp.s

geometry.o: geometry.cpp.o
.PHONY : geometry.o

# target to build an object file
geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/geometry.cpp.o
.PHONY : geometry.cpp.o

geometry.i: geometry.cpp.i
.PHONY : geometry.i

# target to preprocess a source file
geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/geometry.cpp.i
.PHONY : geometry.cpp.i

geometry.s: geometry.cpp.s
.PHONY : geometry.s

# target to generate assembly for a file
geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/geometry.cpp.s
.PHONY : geometry.cpp.s

gl_helper.o: gl_helper.cpp.o
.PHONY : gl_helper.o

# target to build an object file
gl_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/gl_helper.cpp.o
.PHONY : gl_helper.cpp.o

gl_helper.i: gl_helper.cpp.i
.PHONY : gl_helper.i

# target to preprocess a source file
gl_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/gl_helper.cpp.i
.PHONY : gl_helper.cpp.i

gl_helper.s: gl_helper.cpp.s
.PHONY : gl_helper.s

# target to generate assembly for a file
gl_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/gl_helper.cpp.s
.PHONY : gl_helper.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/main.cpp.s
.PHONY : main.cpp.s

trackball_ctrl.o: trackball_ctrl.cpp.o
.PHONY : trackball_ctrl.o

# target to build an object file
trackball_ctrl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/trackball_ctrl.cpp.o
.PHONY : trackball_ctrl.cpp.o

trackball_ctrl.i: trackball_ctrl.cpp.i
.PHONY : trackball_ctrl.i

# target to preprocess a source file
trackball_ctrl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/trackball_ctrl.cpp.i
.PHONY : trackball_ctrl.cpp.i

trackball_ctrl.s: trackball_ctrl.cpp.s
.PHONY : trackball_ctrl.s

# target to generate assembly for a file
trackball_ctrl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WaterShader.dir/build.make CMakeFiles/WaterShader.dir/trackball_ctrl.cpp.s
.PHONY : trackball_ctrl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WaterShader"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... gl_helper.o"
	@echo "... gl_helper.i"
	@echo "... gl_helper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... trackball_ctrl.o"
	@echo "... trackball_ctrl.i"
	@echo "... trackball_ctrl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

